apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springbootwebapp
  name: springbootwebapp  
  namespace: springbootwebapp  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootwebapp
  template:
    metadata:
      labels:
        app: springbootwebapp
    spec:
      containers:
        - name: springbootwebapp
          image: '400603430485.dkr.ecr.ap-northeast-2.amazonaws.com/springbootwebapp'
          ports:
            - containerPort: 8080
              name: http
