apiVersion: v1
kind: Service
metadata:
  name: springbootwebapp
  namespace: springbootwebapp
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: springbootwebapp
